require 'hive/worker'

module Hive
  class Worker
    # The Shell worker
    class Shell < Worker
      def initialize(options = {})
        super
      end

      def pre_script(job, file_system, script)
      end

      # List of autogenerated queues for the worker
      def autogenerated_queues
        @options['queues']
      end

    end
  end
end
